CREATING DATAFRAME

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [4]:
 df = pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [10]:
df2 =  pd.DataFrame(data_list)

In [11]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [15]:
columns = ['name','age','city','salary']
df2 =  pd.DataFrame(data_list,columns = columns)

In [16]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

In [17]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2[['name','city']]

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [20]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

creating new column

In [21]:
df2['designation'] = ['hr','it','da','ds']

In [22]:
df2

    name  age      city  salary designation
0   John   28  New York   65000          hr
1   Anna   34     Paris   70000          it
2  Peter   29    Berlin   62000          da
3  Linda   42    London   85000          ds

removing  column

In [32]:
df2.drop('designation', axis= 1,inplace=True)

In [33]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

SELECTING ROWS

In [36]:
df2.loc[0]

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [37]:
df2.iloc[0]

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [40]:
df2.iloc[[0,1]]

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [41]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [42]:
df2.iloc[[0,1]][['city','salary']]

       city  salary
0  New York   65000
1     Paris   70000

In [43]:
df2.iloc[[2,3]][['name','age']]

    name  age
2  Peter   29
3  Linda   42

CONDITIONAL SELECTION

In [44]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

i want people of age greater then 30

In [49]:
df2[df2['age'] > 30 ]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

i want people of age greater then 30 and living in paris

In [52]:
df2[(df2['age'] > 30) & (df2['city'] == 'Paris') ]

   name  age   city  salary
1  Anna   34  Paris   70000