DataFrames Basic Operations

In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df1.shape

(5, 3)

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [8]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [9]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [11]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

DataFrames Applying Functions

In [13]:
def sqaure(x):
    return x**2

In [14]:
df1['B'] = df1['B'].apply(sqaure)

In [15]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [16]:
df1['D'] = df1['B'].apply(lambda  x: x**2)

In [17]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000